### ISSUE TITLE
Problem with Broadcasting transaction

### ISSUE THREAD

**Issue by maxcado** [balzac-lang/balzac#69]
I've tried using the online editor at blockchain.unica.it/balzac/. Using the testnent example 'Signature modifiers'. Tried to broadcast the transaction at an explorer and the response was that some inputs are not there. 

What's the best explorer to broadcast?

**Comment by natzei** [comment]
Hi @maxcado, there is no best explorer to choose, every explore should work fine.

If you tried to broadcast the example 'Signature modifiers' as is, the failure is due to the usage of the fake coinbase transactions:

```
// simple coinbase 1
transaction T_input1 {
    input = _
    output = 1 BTC: fun(x) . x == 42
}

// simple coinbase 2
transaction T_input2 {
    input = _
    output = 1 BTC: fun(x) . x != 0
}
```

They must be replaced with real bitcoin transactions. Please refer to the documentation [Real transactions as Input](https://docs.balzac-lang.xyz/raw-transactions.html#real-transactions-as-input)
